flow

diff --git a/deployments/dev/project1/env0.yml b/deployments/dev/project1/env0.yml
--- a/deployments/dev/project1/env0.yml
+++ b/deployments/dev/project1/env0.yml
@@ -32,14 +32,21 @@ deploy:
               echo "TF_CLOUD_WORKSPACE_ID $TF_CLOUD_WORKSPACE_ID"
             fi
 
+            mkdir -p "terraform.tfstate.d/${ENV0_WORKSPACE_NAME}"
+
             echo "fetching latest state info"
-            STATE_DOWNLOAD_URL=$(curl --fail-with-body \
+            STATE_DOWNLOAD_URL=$(curl -sfS --fail-with-body \
               --header "Authorization: Bearer $TF_CLOUD_TOKEN" \
               --header "Content-Type: application/vnd.api+json" \
               https://app.terraform.io/api/v2/workspaces/${TF_CLOUD_WORKSPACE_ID}/current-state-version | jq '.data.attributes["hosted-state-download-url"]' -r)
 
             # this call does not require auth?
-            curl --fail-with-body $STATE_DOWNLOAD_URL -o $WORKSPACE_STATE_PATH
+            curl -sfS $STATE_DOWNLOAD_URL -o $WORKSPACE_STATE_PATH
+            
+            if [ $? -ne 0 ];then
+              echo "curl failed, exiting"
+              exit 1
+            fi
 
             echo "migrated"
           fi
